### ISSUE TITLE
Please add MIT license

### ISSUE THREAD

**Issue by kattkieru** [jeuxdemains/DOOM-like-game-engine-part-I#1]
Hi there,

Great video!  A permissive license like MIT or BSD would be appreciated.

**Comment by jeuxdemains** [comment]
Oh, sure! I didn't thought of that. I'll add it. But feel free to fork it, hack it, and generally have fun with it in any way you like.

**Comment by jeuxdemains** [comment]
Done!

**Comment by kattkieru** [comment]
Amazing, thank you!  Looking forward to your takes on span sorting, sprites, BSP, and actual portals. :)
